#!/usr/bin/env bash
set -euo pipefail

CONFIG_FILE="${1:-scripts/init/config.env}"
if [[ ! -f "$CONFIG_FILE" ]]; then
  echo "[ERROR] config file not found: $CONFIG_FILE"
  echo "cp scripts/init/config.template.env scripts/init/config.env 후 값을 수정하세요."
  exit 1
fi

# shellcheck disable=SC1090
source "$CONFIG_FILE"

TARGET_DIR="${TARGET_DIR:-.}"
APP_NAME="${APP_NAME:-KMPApp}"
BASE_PACKAGE="${BASE_PACKAGE:-com.example.kmpapp}"
ENABLE_IOS="${ENABLE_IOS:-true}"
ENABLE_SERVER="${ENABLE_SERVER:-true}"

mkdir -p "$TARGET_DIR"/{composeApp,shared,docs/00-policy,scripts}
[[ "$ENABLE_IOS" == "true" ]] && mkdir -p "$TARGET_DIR/iosApp"
[[ "$ENABLE_SERVER" == "true" ]] && mkdir -p "$TARGET_DIR/server"

cat > "$TARGET_DIR/README.md" <<EOT
# $APP_NAME

Generated by KMPForge.

## Modules
- composeApp
- shared
$([[ "$ENABLE_SERVER" == "true" ]] && echo "- server")
$([[ "$ENABLE_IOS" == "true" ]] && echo "- iosApp")

## Package
- $BASE_PACKAGE
EOT

cat > "$TARGET_DIR/.bootstrap-meta" <<EOT
APP_NAME=$APP_NAME
BASE_PACKAGE=$BASE_PACKAGE
ENABLE_IOS=$ENABLE_IOS
ENABLE_SERVER=$ENABLE_SERVER
EOT

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [[ -x "$SCRIPT_DIR/sync-required-skills.sh" ]]; then
  "$SCRIPT_DIR/sync-required-skills.sh" "$TARGET_DIR" || true
fi

echo "[OK] bootstrap complete: $TARGET_DIR"
